version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: posgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mediconnect
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mediconnect-network

  patient-api:
    build:
      context: ./patient-api
    container_name: patient-api
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - mediconnect-network

  condition-api:
    build:
      context: ./condition-api
    container_name: condition-api
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      - mediconnect-network

volumes:
  pgdata:

networks:
  mediconnect-network:
    driver: bridge
